### PR TITLE
Remove sensitive data from public repository

### PR DESCRIPTION
**Pull request by BlakeStevenson**
Abuse of your API credentials by a third party could lead to termination of your reddit account. Cool to see you using my code by the way! 😀

### CODE REVIEW

**Comment by BlakeStevenson** [comment]
Unrelated to the PR, but it would be better to cache memes, rather than scraping them on page load. If you scrape them on page load, it will cause the page load time to suffer. This is what I did with my version, I setup a cron job to run every six hours, deleting the existing memes and running the script to fetch new ones. I also set my web application to run asynchronously, rendering the webpage before programmatically executing the cron job to ensure that there would be fresh memes on the next page load.

**Review by reaper6947 — APPROVED** [review]

**Comment by reaper6947** [comment]
thanks a lot,  i actually started this project because i saw your code . i
was frustrated sending memes to my friends , and reddit is actually blocked
where i am from , i am totally new to development and everything is self
taught , i plan on learning more js and implementing a better ui

**Review by reaper6947 — COMMENTED** [review]
thanks for the help

**Comment by reaper6947** [comment]
Please show me master . Sent from Mail for Windows 10 From: Blake StevensonSent: Friday, November 29, 2019 3:31 AMTo: reaper6947/reddit-meme-webpageCc: SubscribedSubject: Re: [reaper6947/reddit-meme-webpage] Remove sensitive data from public repository (#1) Unrelated to the PR, but it would be better to cache memes, rather than scraping them on page load. If you scrape them on page load, it will cause the page load time to suffer. This is what I did with my version, I setup a cron job to run every six hours, deleting the existing memes and running the script to fetch new ones. I also set my web application to run asynchronously, rendering the webpage before programmatically executing the cron job to ensure that there would be fresh memes on the next page load.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
